server:
  port: 8081

spring:
  application:
    name: facture

  datasource:
    url: jdbc:postgresql://localhost:5432/facture
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


